In [1]:
import warnings
warnings.filterwarnings("ignore")
import wrangle as w

import pandas as pd
import numpy as np

#splits
from sklearn.model_selection import train_test_split

#visualization
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns

#scaling
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.metrics import precision_score, accuracy_score, recall_score, classification_report

#model
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.linear_model import LogisticRegression
import kc_wrangle as w
import wrangle as ww

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sqlalchemy import text, create_engine

import warnings
warnings.filterwarnings("ignore")

np.random.seed(42)

In [10]:
df = pd.read_csv("merged_data - merged_data.csv")

In [11]:
df, model_df = ww.prep_df(df)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110079 entries, 0 to 197201
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   dob            110079 non-null  datetime64[ns]
 1   outcome        110079 non-null  object
 2   sex            110079 non-null  object
 3   name           110079 non-null  int64
 4   intake_type    110079 non-null  object
 5   condition      110079 non-null  object
 6   species        110079 non-null  object
 7   breed          110079 non-null  object
 8   outcome_age    110079 non-null  int64
 9   rel_month      110079 non-null  object
 10  rel_year       110079 non-null  object
 11  primary_color  110079 non-null  object
 12  is_tabby       110079 non-null  int64
 13  mix_color      110079 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(9)
memory usage: 12.6+ MB

In [6]:
model_df.head()

,name,outcome_age,is_tabby,mix_color,outcome_other,outcome_transfer,sex_intact male,sex_neutered male,sex_spayed female,intake_type_euthanasia request,...,primary_color_gray,primary_color_lilac point,primary_color_lynx point,primary_color_orange,primary_color_red,primary_color_sable,primary_color_seal point,primary_color_tan,primary_color_tricolor,primary_color_white
0,1,736,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,371,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
5,1,6,1,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,1,797,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
9,1,76,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
# create dummies
dummy_df = pd.get_dummies(df[['outcome', 'sex','intake_type', 'condition',
                             'species', 'breed', 'rel_month', 'rel_year', 'primary_color']],
                          drop_first=True)
bool_df = df[['name', 'outcome_age', 'is_tabby', 'mix_color']]

m_df = pd.concat([bool_df, dummy_df], axis=1)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110079 entries, 0 to 197201
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   dob            110079 non-null  datetime64[ns]
 1   outcome        110079 non-null  object
 2   sex            110079 non-null  object
 3   name           110079 non-null  int64
 4   intake_type    110079 non-null  object
 5   condition      110079 non-null  object
 6   species        110079 non-null  object
 7   breed          110079 non-null  object
 8   outcome_age    110079 non-null  int64
 9   rel_month      110079 non-null  object
 10  rel_year       110079 non-null  object
 11  primary_color  110079 non-null  object
 12  is_tabby       110079 non-null  int64
 13  mix_color      110079 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(9)
memory usage: 12.6+ MB

In [9]:
df = pd.concat([df, dummy_df], axis=1)
# rename columns
df = df[["partner_Yes", "dependents_Yes", "paperless_billing_Yes", "automatic_payment", "churn_Yes", "tenure"]]

df = df.rename(columns={"partner_Yes": "partner", "dependents_Yes": "dependents", "paperless_billing_Yes": "paperless_billing", "churn_Yes": "churn"})
# df for modeling

KeyError: "None of [Index(['partner_Yes', 'dependents_Yes', 'paperless_billing_Yes',\n       'automatic_payment', 'churn_Yes', 'tenure'],\n      dtype='object')] are in the [columns]"

In [ ]:
model_df.shape

In [ ]:
df.columns

In [ ]:
model_df

In [ ]:
df.head()

In [ ]:
# longhair maybe later
df['breed'].str.contains('longhair', case=False).astype(int).value_counts()

In [ ]:
df.breed.value_counts()